Add AUR package tip
lantw44/ceiba-dl pull request #1
Opened 2017-09-03 18:09 UTC by yan12125

2017-09-04 04:41 UTC, lantw44 requested changes
可以在 commit 訊息開頭加上 `readme: ` 分類嗎？
改的時候請直接 `git push --force` 蓋掉原本的 commit。

2017-09-04 04:41 UTC, lantw44 commented on README.asciidoc
> +如果是Arch Linux的使用者，可以直接從AUR安裝
建議在中英文交接的地方加個空格，這樣感覺會比較好讀。

2017-09-04 04:43 UTC, lantw44 commented
另外 AUR 上的套件 license 應該要填 LGPL3 而不是 GPL3。

2017-09-05 09:41 UTC, yan12125 commented
感謝，已更新。

> 另外 AUR 上的套件 license 應該要填 LGPL3 而不是 GPL3。

我看到這個repo裡有COPYING和COPYING.GPL兩個檔案。我當初應該是參考COPYING.GPL填寫license的。請問是否能將COPYING.GPL移除，以避免誤解？

另外，ceiba-dl.py中有以下的註解：

```
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
```
或許也可將GNU General Public License改為GNU Lesser General Public License。

2017-09-05 11:39 UTC, lantw44 approved these changes

2017-09-05 11:44 UTC, lantw44 commented
> 感謝，已更新。

已經 push 到 master branch 囉：commit d0e5ea2

> 
>     另外 AUR 上的套件 license 應該要填 LGPL3 而不是 GPL3。
> 
> 我看到這個repo裡有COPYING和COPYING.GPL兩個檔案。我當初應該是參考COPYING.GPL填寫license的。請問是否能將COPYING.GPL移除，以避免誤解？
> 

這沒辦法，因為 LGPL3 的文件本身有參考到 GPL3，所以兩個要一起放才會完整。

> 另外，ceiba-dl.py中有以下的註解：
> ```
> # You should have received a copy of the GNU General Public License
> # along with this program.  If not, see <http://www.gnu.org/licenses/>.
> ```
> 或許也可將GNU General Public License改為GNU Lesser General Public License。

感謝提醒，已經修正了：commit 958f7c1

2017-09-05 11:44 UTC, merged

2017-09-05 12:50 UTC, yan12125 commented
謝謝！AUR上的license也改為正確的版本了。