Fix MacOS related issue, add requirements.txt and fix the wrong time slots
lantw44/ceiba-dl pull request #11
Opened 2019-08-09 13:34 UTC by jimlinntu

2019-08-09 14:34 UTC, lantw44 requested changes
> Fix that MacOS default OpenSSL is using LibreSSL

macOS，然後 using 應該是多餘的？

> Add `python` requirements.txt

Git commit 訊息是純文字不是 markdown，請不要在這裡用 ` 符號。

> Fix README's format

這整個 commit 應該都只是在修前一個 commit 的小錯誤？如果是的話，請直接併入前一個 commit。

> Fix the wrong time slot issue in ceiba_dl/vfs.py

檔名或分類請放開頭，例如「vfs: Update time slots」這樣。

2019-08-09 14:34 UTC, lantw44 commented on README.asciidoc
> +請執行 `pip install -r requirements.txt` 安裝所需套件, 所需 `python` 套件如下:
我們可以加上 `requirements.txt`，但是不要寫得好像一定要用 pip 安裝才行。事實上我自己在寫這個程式的時候是沒有使用 pip 的。我覺得這句話應該要移到清單的下面會比較合適，畢竟 Python 本身並不是個 python 套件。

2019-08-09 14:34 UTC, lantw44 commented on README.asciidoc
> +=== 我的 `pycurl` 在 MacOS 裝不起來, 有顯示 `ImportError: pycurl: libcurl link-time ssl backend (openssl) is different from compile-time ssl backend (none/other)`
安裝問題好像移到上面一點會比較好，下面列的幾乎都是執行時的問題。然後應該是 macOS 不是 MacOS 吧？

2019-08-09 14:34 UTC, lantw44 commented on README.asciidoc
> +簡單來說, 請先把 `pycurl` 卸載後再加上些環境變數後並重裝
請用中文全型標點，句子結尾請加句號。另外這裡用「卸載」感覺有些奇怪，「解除安裝」或「刪除」應該比較符合使用習慣。

2019-08-09 14:34 UTC, lantw44 commented on README.asciidoc
> +[source,bash]
看不出這裡哪裡有使用到 bash 特有的語法，應該用 sh 就可以了吧。

2019-08-09 14:34 UTC, lantw44 commented on README.asciidoc
> +pip3 uninstall pycurl
Git 說這裡有行尾空白。

2019-08-09 14:34 UTC, lantw44 commented on README.asciidoc
> +export CPPFLAGS=-I/usr/local/opt/openssl/include # openssl相關標投檔文件路徑
openssl → OpenSSL
標投檔 → 標頭檔
中英文之間請空一格。「文件」好像是多寫的？

2019-08-09 14:34 UTC, lantw44 commented on README.asciidoc
> +---------------------------------------------------------------------------
這路徑看起來很像是 Homebrew，是否應該註明一下？畢竟並不是所有 macOS 使用者都是用 Homebrew。

2019-08-09 14:34 UTC, lantw44 commented on README.asciidoc
> +
Git 說這裡有檔尾空行。

2019-08-09 14:34 UTC, lantw44 commented on requirements.txt
> +lxml==4.4.0
請不要寫死版號，至少到目前為止我還沒遇過因為版本不合而無法執行的，寫了固定版號會讓使用者以為只能用這幾個版本。

2019-08-09 14:34 UTC, lantw44 commented on ceiba_dl/vfs.py
> +        slots = '01234@56789XABCD' # 節次 (possible time slot: See https://nol.ntu.edu.tw/nol/guest/index.php for more information)
slot → slots

2019-08-13 14:35 UTC, jimlinntu commented
Fix the issues mentioned above.

2019-08-19 15:04 UTC, lantw44 requested changes

2019-08-19 15:04 UTC, lantw44 commented on README.asciidoc
> +欲知道詳細套件及相對應版本, 請查看 link:./requirements.txt[requirements.txt]
這個…… 首先 `requirements.txt` 裡面沒有也不需要記錄版本，再來是 `requirements.txt` 實際上並沒有比 README 詳細。也許可以改成「如果你使用 `pip` 管理 Python 套件，可以執行 `pip install -r requirements.txt` 來安裝以上的函式庫。」？

2019-08-19 15:04 UTC, lantw44 commented on README.asciidoc
> +=== 我的 `pycurl` 在 macOS 裝不起來, 有顯示 `ImportError: pycurl: libcurl link-time ssl backend (openssl) is different from compile-time ssl backend (none/other)`
```suggestion
=== 我的 `pycurl` 在 macOS 裝不起來，顯示 `ImportError: pycurl: libcurl link-time ssl backend (openssl) is different from compile-time ssl backend (none/other)`
```

2019-08-19 15:04 UTC, lantw44 commented on README.asciidoc
> +簡單來說, 請先把 `pycurl` 解除安裝後後再加上些環境變數後並重裝, 如果你的 `python` 套件管理器是 `pip` 的話
```suggestion
簡單來說，請先把 `pycurl` 解除安裝後再加上環境變數並重裝。如果你的 `python` 套件管理器是 `pip` 的話：
```

2019-08-21 14:15 UTC, jimlinntu commented on README.asciidoc
> +欲知道詳細套件及相對應版本, 請查看 link:./requirements.txt[requirements.txt]
好主意！我當初加了這個就是因為我覺得這樣裝比較方便！

2019-09-19 13:57 UTC, lantw44 commented
你的 pull request 還沒 merge 喔，有打算什麼時候更新嗎？

2019-09-20 02:55 UTC, jimlinntu commented
已經更新囉！

2019-09-20 12:47 UTC, merged

2019-09-20 12:51 UTC, lantw44 commented
全部進 master branch 了，最後有個標點符號的小問題我自己用 365e956eaad44cc553c6546ef0686824a5350539 修了。