vfs: 在教師資訊中，對於 0 以外的 msid 皆顯示為「其他授課教師」
lantw44/ceiba-dl pull request #3
Opened 2017-09-22 15:56 UTC by yan12125

嘗試列出「心理與神經資訊學」的教師資訊時發生AssertionError
```
$ ./ceiba-dl ls /課程/104-1/心理與神經資訊學/教師資訊
Traceback (most recent call last):
  File "./ceiba-dl", line 243, in <module>
    exit(0 if args.func(args, config) else 1)
  File "./ceiba-dl", line 158, in run_ls
    lser.run(sys.stdout, path)
  File "/home/yen/Projects/ceiba-dl/ceiba_dl/__init__.py", line 433, in run
    self.print_file(output, path, self.recursive)
  File "/home/yen/Projects/ceiba-dl/ceiba_dl/__init__.py", line 397, in print_file
    node = self.vfs.open(path)
  File "/home/yen/Projects/ceiba-dl/ceiba_dl/vfs.py", line 39, in open
    work.fetch()
  File "/home/yen/Projects/ceiba-dl/ceiba_dl/vfs.py", line 3001, in fetch
    assert False
AssertionError
```

API回傳的結果中，這位老師的msid為2。我登入CEIBA App查看，發現此門課的教師有三個，名字皆為同一人（黃從仁），第一個標示為主要授課老師，另外兩個標示為其他授課教師，因此我推測只有0為主要授課老師。

2017-09-22 16:18 UTC, lantw44 commented
這整個程式都是這樣用 assert 來 debug 的，所以我覺得 `assert False` 還是保留下來比較好。

如果目前還看不出來 CEIBA API 的 tr_msid 欄位 1 或 2 有什麼差別的話，我想比較好的作法是去 config 加個 value_course_teachers_tr_msid_2，再把 2 當成合理的數值來處理。value_course_teachers_tr_msid_2 的預設值就先跟 value_course_teachers_tr_msid_1 一樣都是「其他授課教師」，如果之後找出差別了再修改。

2017-09-23 15:52 UTC, yan12125 commented
謝謝，已修正！

2017-09-23 15:58 UTC, lantw44 requested changes
可以把 2 獨立出來嗎？這樣假設真的有人知道 2 代表什麼意思，可以直接改設定檔換掉名稱而不用來改 code。

2017-09-23 16:49 UTC, yan12125 commented
我將msid=2的case獨立出來了。目前並沒有將重複的code合併，或許等之後msid的定位更明確的時候可以再去精簡code。

2017-09-23 16:55 UTC, lantw44 approved these changes

2017-09-23 16:57 UTC, merged